<template><section class="workbench-task-center"><header><strong>任务中心</strong><button v-for="tab in tabs" :key="tab.id" type="button" :aria-selected="activeTab === tab.id" @click="emit('update:activeTab', tab.id)">{{ tab.label }}</button></header><div><button v-for="row in visibleRows" :key="row.key" type="button" :data-task-key="row.key" @click="emit('select-task', row.modelId, row.task.task_id)"><span>{{ row.task.task_id }}</span><strong>{{ row.label }}</strong><small>{{ row.task.message || row.primaryMetric || "--" }}</small><em>{{ row.primaryMetric || `${row.task.progress}%` }}</em><i>{{ row.statusLabel }}</i></button><p v-if="!visibleRows.length">暂无任务</p></div></section></template>
<script setup lang="ts">
import { computed } from "vue";
import type { TaskCenterTab } from "../../workbench/useWorkbenchPresentation";
import type { WorkbenchTaskRow } from "../../workbench/taskPresentation";
const props = withDefaults(defineProps<{ rows: readonly WorkbenchTaskRow[]; activeTab?: TaskCenterTab }>(), { activeTab: "running" });
const emit = defineEmits<{ "update:activeTab": [tab: TaskCenterTab]; "select-task": [modelId: WorkbenchTaskRow["modelId"], taskId: string] }>();
const tabs: Array<{ id: TaskCenterTab; label: string }> = [{ id: "running", label: "运行中" }, { id: "history", label: "历史记录" }, { id: "logs", label: "日志" }];
const visibleRows = computed(() => props.activeTab === "running" ? props.rows.filter(({ task }) => task.status === "pending" || task.status === "running") : props.activeTab === "history" ? props.rows.filter(({ task }) => task.status === "finished" || task.status === "failed") : []);
</script>
<style scoped>.workbench-task-center{display:grid;height:100%;grid-template-rows:38px minmax(0,1fr)}header{display:flex;gap:4px;align-items:center;padding:0 8px}header strong{padding:0 8px}header button{padding:6px 12px;border:0;border-radius:980px;background:transparent;color:var(--wb-muted)}header button[aria-selected="true"]{background:var(--wb-surface);color:var(--wb-fg)}section>div{overflow:auto;border-top:1px solid var(--wb-border-soft)}section>div>button{display:grid;width:100%;grid-template-columns:92px 170px 1fr 160px 110px;gap:16px;align-items:center;padding:8px 16px;background:transparent;border:0;border-bottom:1px solid var(--wb-border-soft);text-align:left;color:var(--wb-fg)}small,span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--wb-muted)}em{font-style:normal}i{color:#16a34a;font-style:normal}p{padding:24px;text-align:center;color:var(--wb-meta)}</style>
